oom_score = 0
version = 2

[plugins."io.containerd.grpc.v1.cri"]
sandbox_image = "{{.SandboxImage}}"

[plugins."io.containerd.grpc.v1.cri".containerd]
default_runtime_name = "runc"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
BinaryName = "{{.RuncBinaryPath}}"
SystemdCgroup = true

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.untrusted]
runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.untrusted.options]
BinaryName = "{{.RuncBinaryPath}}"

[plugins."io.containerd.grpc.v1.cri".cni]
bin_dir = "{{.CNIBinDir}}"
conf_dir = "{{.CNIConfDir}}"

[plugins."io.containerd.grpc.v1.cri".registry]
config_path = "/etc/containerd/certs.d"

[plugins."io.containerd.grpc.v1.cri".registry.headers]
X-Meta-Source-Client = ["azure/aks"]

[metrics]
address = "{{.MetricsAddress}}"
